// Song categories with colors
export const categories = [
  { id: "pop", name: "پاپ", color: "bg-primary" },
  { id: "traditional", name: "سنتی", color: "bg-blue" },
  { id: "rap", name: "رپ", color: "bg-purple" },
  { id: "rock", name: "راک", color: "bg-accent" },
  { id: "folk", name: "محلی", color: "bg-secondary" },
  { id: "relaxing", name: "آرامش‌بخش", color: "bg-emerald-500" },
  { id: "sad", name: "غمگین", color: "bg-slate-500" },
  { id: "happy", name: "شاد", color: "bg-amber-500" },
  { id: "remix", name: "ریمیکس", color: "bg-fuchsia-500" },
  { id: "nostalgic", name: "نوستالژیک", color: "bg-rose-500" },
]

// Sample songs with categories
export const songs = [
  {
    id: 1,
    title: "جیگر طلا",
    artist: "دیوار",
    artistSlug: "divar",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "divar-jigar-tala",
    duration: 210,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "happy"],
    special: true,
  },
  {
    id: 2,
    title: "دی میدونه",
    artist: "مجید رضوی",
    artistSlug: "majid-razavi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "majid-razavi-dey-midoone",
    duration: 195,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
    special: true,
  },
  {
    id: 3,
    title: "باهام بد تا کرد",
    artist: "جواد آرا",
    artistSlug: "javad-ara",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "javad-ara-baham-bad-ta-kard",
    duration: 225,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
    special: true,
  },
  {
    id: 4,
    title: "بعد از تو",
    artist: "محسن چاوشی",
    artistSlug: "mohsen-chavoshi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "mohsen-chavoshi-bad-az-to",
    duration: 240,
    audioUrl: "/sample-audio.mp3",
    categories: ["traditional", "sad"],
    special: true,
  },
  {
    id: 5,
    title: "هستی",
    artist: "امیر ماهان",
    artistSlug: "amir-mahan",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "amir-mahan-hasti",
    duration: 180,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "nostalgic"],
    special: true,
  },
  {
    id: 6,
    title: "نداریم از تو بهتر",
    artist: "علیرضا طلیسچی",
    artistSlug: "alireza-talischi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "alireza-talischi-nadarim-az-to-behtar",
    duration: 215,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "happy"],
    special: true,
  },
  {
    id: 7,
    title: "من هر شب",
    artist: "میثم ابراهیمی",
    artistSlug: "meysam-ebrahimi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "meysam-ebrahimi-har-shab",
    duration: 205,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
    special: true,
  },
  {
    id: 8,
    title: "مادر",
    artist: "مرتضی اشرفی",
    artistSlug: "morteza-ashrafi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "morteza-ashrafi-madar",
    duration: 230,
    audioUrl: "/sample-audio.mp3",
    categories: ["traditional", "nostalgic"],
    special: true,
  },
  {
    id: 9,
    title: "عشق تو",
    artist: "رضا صادقی",
    artistSlug: "reza-sadeghi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "reza-sadeghi-eshghe-to",
    duration: 210,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
  },
  {
    id: 10,
    title: "خاطرات",
    artist: "محسن یگانه",
    artistSlug: "mohsen-yeganeh",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "mohsen-yeganeh-khaterat",
    duration: 195,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "nostalgic"],
  },
  {
    id: 11,
    title: "دلتنگی",
    artist: "ماکان بند",
    artistSlug: "macan-band",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "macan-band-deltangi",
    duration: 225,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
  },
  {
    id: 12,
    title: "روزهای خوب",
    artist: "حمید هیراد",
    artistSlug: "hamid-hirad",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "hamid-hirad-roozhaye-khoob",
    duration: 240,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "happy"],
  },
  {
    id: 13,
    title: "بی تو",
    artist: "محسن چاوشی",
    artistSlug: "mohsen-chavoshi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "mohsen-chavoshi-bi-to",
    duration: 180,
    audioUrl: "/sample-audio.mp3",
    categories: ["traditional", "sad"],
  },
  {
    id: 14,
    title: "آرامش",
    artist: "رضا صادقی",
    artistSlug: "reza-sadeghi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "reza-sadeghi-aramesh",
    duration: 215,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "relaxing"],
  },
  {
    id: 15,
    title: "تنهایی",
    artist: "میثم ابراهیمی",
    artistSlug: "meysam-ebrahimi",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "meysam-ebrahimi-tanhaei",
    duration: 205,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
  },
  {
    id: 16,
    title: "عاشقانه",
    artist: "محسن یگانه",
    artistSlug: "mohsen-yeganeh",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "mohsen-yeganeh-asheghaneh",
    duration: 230,
    audioUrl: "/sample-audio.mp3",
    categories: ["pop", "sad"],
  },
  {
    id: 17,
    title: "ریمیکس شاد",
    artist: "دی جی الوان",
    artistSlug: "dj-alvan",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "dj-alvan-happy-remix",
    duration: 250,
    audioUrl: "/sample-audio.mp3",
    categories: ["remix", "happy"],
  },
  {
    id: 18,
    title: "راک ایرانی",
    artist: "کاوه یغمایی",
    artistSlug: "kaveh-yaghmaei",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "kaveh-yaghmaei-iranian-rock",
    duration: 270,
    audioUrl: "/sample-audio.mp3",
    categories: ["rock"],
  },
  {
    id: 19,
    title: "رپ فارسی",
    artist: "هیچکس",
    artistSlug: "hichkas",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "hichkas-persian-rap",
    duration: 260,
    audioUrl: "/sample-audio.mp3",
    categories: ["rap"],
  },
  {
    id: 20,
    title: "آهنگ محلی",
    artist: "سالار عقیلی",
    artistSlug: "salar-aghili",
    cover: "/placeholder.svg?height=300&width=300",
    slug: "salar-aghili-folk-music",
    duration: 220,
    audioUrl: "/sample-audio.mp3",
    categories: ["folk", "traditional"],
  },
]

// Get category by ID
export function getCategoryById(categoryId: string) {
  return categories.find((category) => category.id === categoryId)
}

// Get songs by category
export function getSongsByCategory(categoryId: string) {
  return songs.filter((song) => song.categories.includes(categoryId))
}

// Get song by slug
export function getSongBySlug(slug: string) {
  return songs.find((song) => song.slug === slug)
}

// Get related songs (same artist or categories)
export function getRelatedSongs(song: any, limit = 5) {
  return songs
    .filter(
      (s) =>
        s.id !== song.id &&
        (s.artistSlug === song.artistSlug || s.categories.some((cat: string) => song.categories.includes(cat))),
    )
    .slice(0, limit)
}
